name: Docker Image CI

on:
  schedule:
    - cron: "1 1 28 */1 *"  # Run once a month to test...
  push:
    branches: [ master, test* ]
  pull_request:
    branches: [ master, test* ]

jobs:

  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest ] # macos-13 takes too long to build nest


    steps:
    - uses: actions/checkout@v7

    - name: Setup docker (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker colima
        colima start
    
    - name: Build the base Docker image
      run: |
        cd base
        ./regenerate.sh
        
    - name: Build the simulation Docker image
      run: |
        cd simulation        
        ./generate.sh

    - name: Build the simulationx Docker image
      run: |
        cd simulationx       
        ./generate.sh

    - name: Build the osb Docker image
      run: |
        cd osb       
        ./generate.sh

    - name: Print info on installed packages
      run: |
        docker run -t  neuralensemble/osb   /bin/bash -c "omv list -V" 

    - name: Print info on docker images
      run: |
        df -h
        docker images

    - name: Test a number of repos from OSB
      run: |
        docker run -t  neuralensemble/osb   /bin/bash -c "git clone https://github.com/OpenSourceBrain/PyNNShowcase.git && cd PyNNShowcase && omv find && omv all -V" 
